name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DATABASE_URL: "file:./dev.db"
  AT_SECRET: fluminense
  RT_SECRET: fluminense

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Point to back-end
        run: cd back-end
        
      - name: Install dependencies
        run: npm ci
      
      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Prisma generate
        run: npx prisma generate

      - name: Run tests
        run: npm run test
